FROM ubuntu:latest
# FROM debian:jessie
MAINTAINER bruce potter <bp@us.ibm.com>

ARG SCALA_VERSION

# install build tools: curl, java
RUN apt-get update && apt-get install -y curl openjdk-8-jdk

# install scala
RUN curl -s http://downloads.lightbend.com/scala/$SCALA_VERSION/scala-$SCALA_VERSION.tgz | tar -zx -C /usr/local/share
RUN ln -s `ls -1dr /usr/local/share/scala-2* | head -1` /usr/local/share/scala
ENV PATH="/usr/local/share/scala/bin:$PATH"

# the exchange api war file is built from the Makefile using a cmd like: cd $EXCHANGE_API_DIR && ./sbt package
