name: exchange-unit-testing

on:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    env:
      GOPATH: /home/runner/work/anax/anax/go
      DEBIAN_FRONTEND: noninteractive
      DOCKER_NETWORK: exchange-api-network
      DOCKER_REGISTRY: openhorizon
      EXCHANGE_FE_HEADER: issuer
      EXCHANGE_ROOTPW: ci-password
      POSTGRES_DB: exchange
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11

      - name: Create Docker Env
        run: |
          pwd
          java -version
          
          make .docker-network
          docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_USER=$POSTGRES_USER --network $DOCKER_NETWORK --name postgres postgres
          export POSTGRES_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres)
          sudo mkdir -p /etc/horizon/exchange
          sudo bash -c "echo '{ \"api\": { \"db\": { \"jdbcUrl\": \"jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB\",\"user\": \"$POSTGRES_USER\" }, \"root\": { \"password\": \"$EXCHANGE_ROOTPW\",\"frontEndHeader\": \"$EXCHANGE_FE_HEADER\" } } }' > /etc/horizon/exchange/config.json"
          
          unset SBT_OPTS
          make travis-test
          cat /etc/horizon/exchange/config.json
          docker ps -a
          docker network ls
          make test